version: '3.9'

services:
  backend:
    build: ./backend
    command: flask run --host 0.0.0.0 --port 5000
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
